#!/usr/bin/env bash
# install.sh — bootstrap dotfiles, download binaries, symlink configs
# Usage: ./install.sh [--update] [--link] [--copy] [--remove] [--no-windows] [--cargo] [--claude] [--full] [--cleanup]
#
# --update      Force re-download/rebuild all tools even if already at latest version
# --link        Skip binary downloads, only re-link configs (fast config-only updates)
# --copy        Copy configs instead of symlinking (useful on NTFS or shared servers)
# --remove      Remove all deployed symlinks from $HOME and exit (does not touch binaries)
# --no-windows  Skip Windows/Alacritty PowerShell setup (WSL2 only)
# --cargo       Build ALL Rust tools from source via cargo (slow, disk-heavy; Go/C tools
#               still download). Without this flag, prebuilt releases are used wherever
#               available; cargo/rustup are only bootstrapped when this flag is passed.
# --claude      Install the Claude Code stack: Claude Code itself (native installer),
#               Node.js (only needed here to npm-install ccstatusline), ccstatusline
#               (renders its statusLine), and claude-swap (multi-account switcher for
#               it). None of these are useful without Claude Code, so none install
#               unless this flag or --full is passed — see WANT_CLAUDE_STACK below.
#               Implied by --full; pass this alone on a machine that wants Claude Code
#               but not a full Neovim IDE setup.
# --full        Everything --claude installs, PLUS PowerShell (~190MB self-contained
#               tarball, only needed for Neovim's powershell_es LSP) and Neovim's
#               heavier Mason-managed LSP servers: html/cssls/emmet/bashls/pyright and
#               the whole PHP toolchain (intelephense/phpactor/php-cs-fixer/phpcs) —
#               together ~460MB of Mason packages, via a marker file nvim's config
#               reads (see FULL_INSTALL_MARKER below). Everything else (shell, zellij,
#               git, core CLI tools, nvim itself, ruff) installs either way. Use this
#               on a full IDE workstation; use --claude alone on a machine that just
#               wants Claude Code; leave both off on servers/shared boxes that only
#               need the shell environment.
# --cleanup     Remove stale/orphaned local state that install.sh's own overwrite-in-
#               place downloads never touch: the rustup/cargo toolchain when this run
#               isn't --cargo (only regenerated by --cargo, so it's dead weight
#               otherwise), any $BIN_DIR binary/Zellij-plugin/zsh-plugin/npm-global
#               whose .versions entry no longer matches a tool this script still
#               declares (e.g. a tool removed from CORE_TOOLS/CLI_TOOLS, or ccusage's
#               npm install after it was dropped, or ccstatusline if this run isn't
#               --claude/--full — see WANT_CLAUDE_STACK below), and — when this run
#               isn't --full — pwsh plus the --full-only Mason LSP packages (see --full
#               above) that Neovim may have already downloaded under a previous --full
#               run, and any old Claude Code version binaries left in
#               ~/.local/share/claude/versions/ by its own native self-updater
#               (~300MB+ each, pruned regardless of --claude — once Claude Code is
#               installed, cleaning up its stale old versions doesn't depend on
#               whether this run also wants it reinstalled). Node.js itself is left
#               alone even when orphaned (see the note in cleanup_orphans() — merging
#               its tree back apart from ccstatusline/claude-swap's npm packages isn't
#               safe to automate, so it just warns instead of guessing).
#               Combine with other flags freely; has no effect with --link (the tool
#               arrays it diffs against are never populated without a real run).

set -euo pipefail

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'
log() { echo -e "${CYAN}[dotfiles]${RESET} $*"; }
ok() { echo -e "${GREEN}[✓]${RESET} $*"; }
warn() { echo -e "${YELLOW}[!]${RESET} $*"; }
err() { echo -e "${RED}[✗]${RESET} $*" >&2; }

# ── Args ──────────────────────────────────────────────────────────────────────
FORCE_UPDATE=false
LINK_ONLY=false
USE_COPY=false
DO_REMOVE=false
NO_WINDOWS=false
USE_CARGO=false
INSTALL_CLAUDE=false
FULL_INSTALL=false
DO_CLEANUP=false
for arg in "$@"; do
  case $arg in
  --update) FORCE_UPDATE=true ;;
  --link) LINK_ONLY=true ;;
  --copy) USE_COPY=true ;;
  --remove) DO_REMOVE=true ;;
  --no-windows) NO_WINDOWS=true ;;
  --cargo) USE_CARGO=true ;;
  --claude) INSTALL_CLAUDE=true ;;
  --full) FULL_INSTALL=true ;;
  --cleanup) DO_CLEANUP=true ;;
  *)
    err "Unknown flag: $arg"
    exit 1
    ;;
  esac
done

# --full implies --claude — a full IDE workstation still wants Claude Code, not
# just the heavier nvim LSPs. Computed once here and reused everywhere the two
# flags previously would have needed separate checks (install gating below,
# cleanup_orphans()'s orphan detection).
WANT_CLAUDE_STACK=false
[[ "$FULL_INSTALL" == true || "$INSTALL_CLAUDE" == true ]] && WANT_CLAUDE_STACK=true

# ── Paths ─────────────────────────────────────────────────────────────────────
DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$DOTFILES/bin/.local/bin"
SHARE_DIR="$DOTFILES/bin/.local/share"
LOCAL_BIN="$HOME/.local/bin"
VERSIONS_FILE="$LOCAL_BIN/.versions"
LOCAL_SHARE="$HOME/.local/share"

# ── Platform detection ────────────────────────────────────────────────────────
# Refuse to run in Git Bash / MSYS — symlink semantics break on Windows
if [[ "${OSTYPE:-}" == "msys" || "${OSTYPE:-}" == "cygwin" || "$(uname -s)" == MINGW* ]]; then
  err "Run this script inside WSL, not Git Bash / MSYS."
  err "  wsl -e bash ~/GitHub/dotfiles/install.sh"
  exit 1
fi

OS="linux"
ARCH="x86_64"
[[ "$(uname -s)" == "Darwin" ]] && OS="darwin"
[[ "$(uname -m)" == "aarch64" || "$(uname -m)" == "arm64" ]] && ARCH="aarch64"

IS_WSL=false
if grep -qi microsoft /proc/version 2>/dev/null; then
  IS_WSL=true
fi

log "Platform: ${OS}/${ARCH} | WSL: ${IS_WSL} | Dotfiles: ${DOTFILES}"

# ── GitHub auth ───────────────────────────────────────────────────────────────
# Set GITHUB_TOKEN in your environment to raise the API limit from 60 to 5,000
# requests/hour. Without it, a fresh install with 25+ tools can hit the limit.
GITHUB_AUTH=()
if [[ -n "${GITHUB_TOKEN:-}" ]]; then
  GITHUB_AUTH=(-H "Authorization: Bearer $GITHUB_TOKEN")
  log "GitHub token found — using authenticated API (5,000 req/hr limit)"
else
  warn "No GITHUB_TOKEN set — unauthenticated API limit is 60 req/hr. Set it to avoid rate limiting on fresh installs."
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
for cmd in curl tar unzip; do
  if ! command -v "$cmd" &>/dev/null; then
    err "Required tool not found: $cmd — please install it first."
    exit 1
  fi
done

# zsh is the primary shell (see zsh/.zshenv, zsh/.zshrc) but, unlike nu/starship/
# zellij, has no cross-platform prebuilt release binary this script can download
# — it's a system package everywhere. Deliberately NOT auto-installed via apt
# (see CLAUDE.md's Deliberate Omissions table): require it pre-installed instead.
if ! command -v zsh &>/dev/null; then
  err "zsh not found. Install it first, then re-run install.sh:"
  err "  Debian/Ubuntu: sudo apt install zsh"
  err "  macOS:         brew install zsh"
  err "  Other:         use your distro's package manager"
  exit 1
fi

# ── Git (Linux/WSL) ───────────────────────────────────────────────────────────
# Ubuntu 22.04 ships git 2.34; zdiff3 merge style requires 2.35+.
# The git-core PPA provides the latest stable git on Ubuntu/Debian.
if [[ "$OS" == "linux" ]] && command -v apt-get &>/dev/null; then
  git_ver=$(git --version 2>/dev/null | grep -oP '\d+\.\d+' | head -1) || true
  git_major=${git_ver%%.*}
  git_minor=${git_ver##*.}
  if ((git_major < 2 || (git_major == 2 && git_minor < 35))); then
    log "Upgrading git to 2.35+ (required for zdiff3 merge style)..."
    if sudo add-apt-repository -y ppa:git-core/ppa 2>/dev/null &&
      sudo apt-get update -qq 2>/dev/null &&
      sudo apt-get install -y git 2>/dev/null; then
      ok "git upgraded to $(git --version)"
    else
      warn "git upgrade failed — zdiff3 merge style may not work (non-fatal)"
    fi
  fi
fi

# ── Locale (Linux/WSL) ───────────────────────────────────────────────────────
# WSL2 distros often ship without en_US.UTF-8 generated, causing bash to warn
# "cannot change locale (en_US.UTF-8)" on every subprocess spawn (e.g. from nvim).
if [[ "$OS" == "linux" ]] && command -v locale-gen &>/dev/null; then
  if ! locale -a 2>/dev/null | grep -q "en_US.utf8"; then
    log "Generating en_US.UTF-8 locale..."
    if sudo locale-gen en_US.UTF-8 2>/dev/null &&
      sudo update-locale LANG=en_US.UTF-8 2>/dev/null; then
      ok "Locale en_US.UTF-8 generated"
    else
      warn "locale-gen failed — LC_ALL warnings from subprocesses may appear (non-fatal)"
    fi
  fi
fi

# ── Directory setup ───────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR" "$SHARE_DIR" "$LOCAL_BIN" "$LOCAL_SHARE" \
  "$HOME/.ssh/sockets" "$HOME/.cache/starship" "$HOME/.cache/carapace" \
  "$HOME/.local/share/atuin" "$HOME/.config/zsh" "$HOME/.local/share/zsh"
chmod 700 "$HOME/.ssh"
touch "$VERSIONS_FILE"

# ── Version tracking ──────────────────────────────────────────────────────────
get_installed_version() { grep "^$1=" "$VERSIONS_FILE" 2>/dev/null | cut -d= -f2 || echo ""; }
set_installed_version() {
  local key="$1" ver="$2"
  if grep -q "^${key}=" "$VERSIONS_FILE" 2>/dev/null; then
    sed -i "s|^${key}=.*|${key}=${ver}|" "$VERSIONS_FILE"
  else
    echo "${key}=${ver}" >>"$VERSIONS_FILE"
  fi
}

# ── GitHub release downloader ─────────────────────────────────────────────────
# Usage: download_release REPO ASSET_GLOB DEST_BIN [BINARY_IN_ARCHIVE]
# ASSET_GLOB: shell glob matching the archive filename, e.g. "bat-*-x86_64*linux*musl*.tar.gz"
# DEST_BIN:   filename to create in BIN_DIR
# BINARY_IN_ARCHIVE: path inside archive to the binary (default: same as DEST_BIN)
download_release() {
  local repo="$1" glob="$2" dest="$3" bin_in_archive="${4:-$3}"
  local key="${dest}"
  local installed
  installed=$(get_installed_version "$key")

  log "Checking ${dest}..."

  # Skip the API call entirely when already installed and not forcing update.
  # With 25+ tools and 60 unauthenticated requests/hour, making an API call for
  # every tool on every run burns the rate limit and causes tools past ~tool 10
  # to never record their version in .versions (they get "Could not fetch" and
  # return early, leaving installed="" on the next run → re-download loop).
  if [[ -n "$installed" && "$FORCE_UPDATE" == false ]]; then
    ok "${dest} already at ${installed}"
    return
  fi

  # Single API call — parse both tag_name and asset URLs from one response.
  local api_response
  api_response=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
    "${GITHUB_AUTH[@]}" "https://api.github.com/repos/${repo}/releases/latest") || true

  local latest
  latest=$(echo "$api_response" | grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
  if [[ -z "$latest" ]]; then
    warn "Could not fetch latest version for ${repo} — skipping."
    return
  fi

  if [[ "$installed" == "$latest" && "$FORCE_UPDATE" == false ]]; then
    ok "${dest} already at ${latest}"
    return
  fi

  log "Downloading ${dest} ${latest}..."

  # Convert shell glob wildcards (*) to grep extended-regex (.*) for proper matching
  local regex="${glob//\*/.*}"

  # Find the matching asset URL from the cached API response
  local asset_url
  asset_url=$(echo "$api_response" |
    grep '"browser_download_url"' |
    grep -v '\.sha256\|\.sha512\|\.asc\|\.sig\|checksums\|\.deb\|\.rpm\|\.msi\|\.dmg\|\.pkg\|-apple-darwin\|windows\|\.exe\|android' |
    grep -iE "$regex" |
    head -1 |
    cut -d'"' -f4) || true

  if [[ -z "$asset_url" ]]; then
    # Fallback: /releases/latest may have no assets on some repos. Try the
    # releases list and take the newest release that has a matching asset.
    local releases_response
    releases_response=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
      "${GITHUB_AUTH[@]}" "https://api.github.com/repos/${repo}/releases?per_page=5") || true
    asset_url=$(echo "$releases_response" |
      grep '"browser_download_url"' |
      grep -v '\.sha256\|\.sha512\|\.asc\|\.sig\|checksums\|\.deb\|\.rpm\|\.msi\|\.dmg\|\.pkg\|-apple-darwin\|windows\|\.exe\|android' |
      grep -iE "$regex" |
      head -1 |
      cut -d'"' -f4) || true
    if [[ -n "$asset_url" ]]; then
      # Extract version from the URL for tracking
      latest=$(echo "$releases_response" | grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
    fi
  fi

  if [[ -z "$asset_url" ]]; then
    warn "No matching asset found for ${dest} (pattern: ${glob}) — skipping."
    return
  fi

  local tmpdir
  tmpdir=$(mktemp -d)
  trap "rm -rf '$tmpdir'" RETURN

  local archive="${tmpdir}/archive"
  if ! curl -fL --connect-timeout 30 --max-time 600 --retry 2 "$asset_url" -o "$archive"; then
    warn "Download failed for ${dest} — skipping."
    return
  fi

  # Detect archive type and extract
  local extracted_binary
  if [[ "$asset_url" == *.tar.gz || "$asset_url" == *.tgz ]]; then
    tar -xzf "$archive" -C "$tmpdir"
    extracted_binary=$(find "$tmpdir" -name "$bin_in_archive" -not -name "*.gz" | head -1)
  elif [[ "$asset_url" == *.tar.xz ]]; then
    tar -xJf "$archive" -C "$tmpdir"
    extracted_binary=$(find "$tmpdir" -name "$bin_in_archive" | head -1)
  elif [[ "$asset_url" == *.zip ]]; then
    unzip -q "$archive" -d "$tmpdir"
    extracted_binary=$(find "$tmpdir" -name "$bin_in_archive" | head -1)
  else
    # Plain binary
    extracted_binary="$archive"
  fi

  if [[ -z "$extracted_binary" || ! -f "$extracted_binary" ]]; then
    warn "Could not find '${bin_in_archive}' in archive for ${dest} — skipping."
    return
  fi

  install -m 755 "$extracted_binary" "$BIN_DIR/$dest"
  set_installed_version "$key" "$latest"
  ok "${dest} installed at ${latest}"
}

# ── Node.js installer (from nodejs.org, not a GitHub release) ─────────────────
# Node is a runtime *tree* (bin/node + lib/node_modules/npm, with npm/npx as
# relative symlinks into lib), not a single binary, so download_release can't
# handle it. Installs the latest LTS straight into ~/.local/{bin,lib,include,
# share} as real files (outside the dotfiles symlink tree, so prune/link never
# touch it). This is what unblocks Mason's npm-based LSP servers (html, css,
# emmet, bash, intelephense, pyright). ~/.local/bin is already prepended ahead
# of the Windows nodejs path in zsh/.zshenv, so the Linux `npm` wins.
install_node() {
  local key="node" installed latest
  installed=$(get_installed_version "$key")

  log "Checking node..."

  # Latest LTS from the dist index, without jq: each release object ends in '}',
  # so split per object, keep those with a string "lts":"Name" (false has no
  # quote after the colon), take the newest (index is newest-first).
  latest=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
    "https://nodejs.org/dist/index.json" |
    tr '}' '\n' | grep '"lts":"' |
    grep -oP '"version":\s*"\Kv[^"]+' | head -1) || true
  if [[ -z "$latest" ]]; then
    warn "Could not determine latest Node LTS — skipping."
    return
  fi
  if [[ "$installed" == "$latest" && "$FORCE_UPDATE" == false ]]; then
    ok "node already at ${latest}"
    return
  fi

  local node_os node_arch
  case "$OS" in
  linux) node_os="linux" ;;
  darwin) node_os="darwin" ;;
  *)
    warn "Unsupported OS for Node.js (${OS}) — skipping."
    return
    ;;
  esac
  case "$ARCH" in
  x86_64) node_arch="x64" ;;
  aarch64) node_arch="arm64" ;;
  *)
    warn "Unsupported arch for Node.js (${ARCH}) — skipping."
    return
    ;;
  esac

  local base="node-${latest}-${node_os}-${node_arch}"
  local url="https://nodejs.org/dist/${latest}/${base}.tar.xz"
  local tmpdir
  tmpdir=$(mktemp -d)
  trap "rm -rf '$tmpdir'" RETURN

  log "Downloading Node.js ${latest} (${node_os}-${node_arch})..."
  if ! curl -fL --connect-timeout 30 --max-time 600 --retry 2 "$url" -o "$tmpdir/node.tar.xz"; then
    warn "Node.js download failed — skipping."
    return
  fi
  if ! tar -xJf "$tmpdir/node.tar.xz" -C "$tmpdir"; then
    warn "Node.js extract failed — skipping."
    return
  fi

  local root="$tmpdir/$base"
  if [[ ! -d "$root/bin" ]]; then
    warn "Unexpected Node.js archive layout — skipping."
    return
  fi

  # Merge into ~/.local, preserving the relative npm/npx symlinks (cp -a).
  mkdir -p "$LOCAL_BIN" "$LOCAL_SHARE" "$HOME/.local/lib" "$HOME/.local/include"
  cp -a "$root/bin/." "$LOCAL_BIN/"
  cp -a "$root/lib/." "$HOME/.local/lib/"
  [[ -d "$root/include" ]] && cp -a "$root/include/." "$HOME/.local/include/"
  [[ -d "$root/share" ]] && cp -a "$root/share/." "$LOCAL_SHARE/"

  set_installed_version "$key" "$latest"
  ok "node installed at ${latest} ($("$LOCAL_BIN/node" --version 2>/dev/null || echo '?'))"
}

# ── ccstatusline (npm CLI; renders the Claude Code statusLine) ────────────────
# Pinned rather than always-latest (unlike the GitHub-release CLI_TOOLS below):
# ccstatusline writes its own installedVersion/method back into
# ~/.config/ccstatusline/settings.json (the "installation" block, deployed as
# part of the ccstatusline package below) and detects drift between that and
# the actual npm-installed version — an unreviewed bump could desync the two
# and trip its own update prompt. Bump deliberately (npm view ccstatusline
# version) and update the "installation" block in
# ccstatusline/.config/ccstatusline/settings.json to match.
install_ccstatusline() {
  local key="ccstatusline"
  local pinned_version="2.2.27"
  local installed
  installed=$(get_installed_version "$key")

  log "Checking ccstatusline..."

  if [[ "$installed" == "$pinned_version" && "$FORCE_UPDATE" == false ]]; then
    ok "ccstatusline already at ${pinned_version}"
    return
  fi

  if ! command -v npm &>/dev/null; then
    warn "npm not found (node install may have failed) — skipping ccstatusline."
    return
  fi

  log "Installing ccstatusline ${pinned_version}..."
  if npm install -g "ccstatusline@${pinned_version}" --prefix "$HOME/.local" &>/dev/null; then
    set_installed_version "$key" "$pinned_version"
    ok "ccstatusline installed at ${pinned_version}"
  else
    warn "ccstatusline install failed — the statusLine will show stale/no data until this succeeds."
  fi
}

# ── Claude Code CLI (native installer) ─────────────────────────────────────────
# Installs via the official native installer (curl | bash from claude.ai/install.sh),
# the same mechanism that already owns ~/.local/bin/claude as a symlink into
# ~/.local/share/claude/versions/<version> — see the cleanup_orphans() note on
# that layout for how old versions there get pruned. The installer self-updates
# in the background on its own, so this only ever bootstraps a fresh install;
# no .versions tracking here (there's nothing meaningful for us to compare
# against — the native updater manages its own version state independently of
# this script). --update runs `claude update` to force an immediate check
# rather than waiting on the background updater.
install_claude() {
  log "Checking claude..."

  if [[ -x "$LOCAL_BIN/claude" ]]; then
    if [[ "$FORCE_UPDATE" == true ]]; then
      if "$LOCAL_BIN/claude" update &>/dev/null; then
        ok "claude updated ($("$LOCAL_BIN/claude" --version 2>/dev/null || echo '?'))"
      else
        warn "claude update failed — it auto-updates in the background regardless"
      fi
    else
      ok "claude already installed ($("$LOCAL_BIN/claude" --version 2>/dev/null || echo '?'))"
    fi
    return
  fi

  log "Installing Claude Code..."
  if curl -fsSL --connect-timeout 15 --retry 2 https://claude.ai/install.sh | bash &>/dev/null; then
    ok "claude installed ($("$LOCAL_BIN/claude" --version 2>/dev/null || echo '?'))"
  else
    warn "Claude Code install failed — install manually: curl -fsSL https://claude.ai/install.sh | bash"
  fi
}

# ── claude-swap (multi-account switcher for Claude Code CLI) ──────────────────
# PyPI-only (no GitHub-release binaries) — installed via `uv tool install`,
# the exact install method the tool's own self-upgrade command (`cswap
# upgrade`) is built to detect and drive. Requires uv, downloaded into
# $BIN_DIR by the CLI_TOOLS loop above; called via that repo-tree path
# directly rather than PATH lookup, since link_package hasn't symlinked it
# into ~/.local/bin yet at this point in the script (same reasoning as the
# bat theme-cache build above). Always-latest like the rest of CLI_TOOLS, not
# pinned like ccstatusline above: nothing here parses claude-swap's output, so
# a version bump can't silently break a script the way an unreviewed
# ccstatusline bump could — `uv tool list` is a local, zero-cost check, so
# it's fine to re-run every invocation instead of gating on the .versions
# cache.
install_claude_swap() {
  if [[ ! -x "$BIN_DIR/uv" ]]; then
    warn "uv not found (uv install may have failed) — skipping claude-swap."
    return
  fi

  log "Checking claude-swap..."
  if [[ "$FORCE_UPDATE" == true ]]; then
    if "$BIN_DIR/uv" tool upgrade claude-swap &>/dev/null ||
      "$BIN_DIR/uv" tool install claude-swap &>/dev/null; then
      ok "claude-swap upgraded"
    else
      warn "claude-swap upgrade/install failed — skipping."
    fi
    return
  fi

  if "$BIN_DIR/uv" tool list 2>/dev/null | grep -q '^claude-swap'; then
    ok "claude-swap already installed"
    return
  fi

  if "$BIN_DIR/uv" tool install claude-swap &>/dev/null; then
    ok "claude-swap installed"
  else
    warn "claude-swap install failed — skipping."
  fi
}

# ── PowerShell installer (self-contained, bundles .NET; from GitHub release) ───
# The PowerShell LSP (powershell_es) just needs `pwsh` on PATH. PowerShell ships
# a self-contained tarball that bundles the .NET runtime — no separate .NET, no
# root. It's a flat app *tree* (~190 MB: pwsh + hundreds of .dlls), not a single
# binary, so it can't use download_release: extract it whole into
# ~/.local/lib/powershell and symlink pwsh into ~/.local/bin. Mason then installs
# the PowerShell Editor Services bundle (a plain download, not pip/npm) and
# powershell_es runs it via pwsh (see nvim plugins/lsp-servers.lua).
install_powershell() {
  local key="pwsh" installed latest tag
  installed=$(get_installed_version "$key")

  log "Checking pwsh..."
  tag=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
    "${GITHUB_AUTH[@]}" "https://api.github.com/repos/PowerShell/PowerShell/releases/latest" |
    grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
  if [[ -z "$tag" ]]; then
    warn "Could not determine latest PowerShell release — skipping."
    return
  fi
  latest="${tag#v}"
  if [[ "$installed" == "$latest" && "$FORCE_UPDATE" == false ]]; then
    ok "pwsh already at ${latest}"
    return
  fi

  local ps_os ps_arch
  case "$OS" in
  linux) ps_os="linux" ;;
  darwin) ps_os="osx" ;;
  *)
    warn "Unsupported OS for PowerShell (${OS}) — skipping."
    return
    ;;
  esac
  case "$ARCH" in
  x86_64) ps_arch="x64" ;;
  aarch64) ps_arch="arm64" ;;
  *)
    warn "Unsupported arch for PowerShell (${ARCH}) — skipping."
    return
    ;;
  esac

  local asset="powershell-${latest}-${ps_os}-${ps_arch}.tar.gz"
  local url="https://github.com/PowerShell/PowerShell/releases/download/${tag}/${asset}"
  local tmpdir
  tmpdir=$(mktemp -d)
  trap "rm -rf '$tmpdir'" RETURN

  log "Downloading PowerShell ${latest} (${ps_os}-${ps_arch})..."
  if ! curl -fL --connect-timeout 30 --max-time 600 --retry 2 "$url" -o "$tmpdir/pwsh.tar.gz"; then
    warn "PowerShell download failed — skipping."
    return
  fi

  # Flat archive → extract the whole tree into a dedicated dir (replace on update).
  local dest="$HOME/.local/lib/powershell"
  rm -rf "$dest"
  mkdir -p "$dest" "$LOCAL_BIN"
  if ! tar -xzf "$tmpdir/pwsh.tar.gz" -C "$dest"; then
    warn "PowerShell extract failed — skipping."
    return
  fi
  chmod +x "$dest/pwsh"
  ln -sf "$dest/pwsh" "$LOCAL_BIN/pwsh"

  set_installed_version "$key" "$latest"
  ok "pwsh installed at ${latest} ($("$LOCAL_BIN/pwsh" -NoProfile -Command '$PSVersionTable.PSVersion.ToString()' 2>/dev/null || echo '?'))"
}

# ── Cargo installer ───────────────────────────────────────────────────────────
# Usage: cargo_install CRATE DEST_BIN
# Installs to dotfiles bin dir via cargo (symlinked to ~/.local/bin by link_package).
# Checks crates.io for the latest version to avoid unnecessary recompiles.
cargo_install() {
  local crate="$1" dest="$2"
  local cargo_bin="$HOME/.cargo/bin/cargo"
  log "Checking ${dest} (cargo)..."
  if [[ ! -x "$cargo_bin" ]]; then
    warn "${dest}: cargo not available — skipping"
    return
  fi
  local latest
  latest=$(curl -sf --connect-timeout 15 \
    -H "User-Agent: dotfiles-install/1.0" \
    "https://crates.io/api/v1/crates/${crate}" |
    grep -oP '"newest_version"\s*:\s*"\K[^"]+' | head -1) || true
  if [[ -z "$latest" ]]; then
    warn "Could not fetch latest version for ${crate} — skipping"
    return
  fi
  local installed
  installed=$(get_installed_version "$dest")
  if [[ -z "$installed" ]]; then
    installed=$("$cargo_bin" install --list --root "$DOTFILES/bin/.local" 2>/dev/null |
      grep -oP "^${crate} v\K[0-9][^:]+") || true
    [[ -n "$installed" ]] && set_installed_version "$dest" "$installed"
  fi
  if [[ "$installed" == "$latest" && "$FORCE_UPDATE" == false ]]; then
    ok "${dest} already at ${latest}"
    return
  fi
  log "Installing ${dest} ${latest} via cargo (compiling from source)..."
  local -a flags=(--root "$DOTFILES/bin/.local" --force)
  # Try --locked first: if the crate published a Cargo.lock it pins transitive
  # deps (e.g. interprocess 1.x) that may otherwise resolve to a breaking version.
  local install_ok=false
  if "$cargo_bin" install "$crate" --locked "${flags[@]}" 2>&1; then
    install_ok=true
  else
    log "Retrying ${dest} without --locked..."
    if "$cargo_bin" install "$crate" "${flags[@]}" 2>&1; then
      install_ok=true
    fi
  fi
  if [[ "$install_ok" == true ]]; then
    set_installed_version "$dest" "$latest"
    ok "${dest} installed at ${latest}"
  else
    warn "cargo install ${crate} failed — skipping"
  fi
}

# ── Generic tool installer ────────────────────────────────────────────────────
# Row format (pipe-separated):
#   dest | crate | repo | os | arch | glob | bin
# os:   linux | darwin
# arch: x86_64 | aarch64 | * (matches any arch for that os)
# crate: cargo crate name, or - if not available via cargo
# bin:  binary name inside archive; defaults to dest when -
# One row per supported platform variant.
declare -A _cargo_done=()
install_tool() {
  local dest crate repo os arch glob bin
  IFS='|' read -r dest crate repo os arch glob bin <<<"$1"
  [[ "$bin" == "-" ]] && bin="$dest"

  if [[ "$USE_CARGO" == true && "$crate" != "-" ]]; then
    if [[ -z "${_cargo_done[$dest]+x}" ]]; then
      cargo_install "$crate" "$dest"
      _cargo_done[$dest]=1
    fi
    return
  fi

  if [[ "$OS" == "$os" ]] && [[ "$arch" == "*" || "$ARCH" == "$arch" ]]; then
    download_release "$repo" "$glob" "$dest" "$bin"
  fi
}

# ── Binary downloads ──────────────────────────────────────────────────────────
if [[ "$LINK_ONLY" == false ]]; then

  # Rust toolchain bootstrap — gated on --cargo. (Previously unconditional: a
  # couple of Nushell plugins shipped no prebuilt binary at all and needed
  # cargo regardless of this flag. Now that nu is gone, cargo/rustup have no
  # other unconditional consumer, so this only runs when --cargo is passed.)
  if [[ "$USE_CARGO" == true ]]; then
    log "=== Rust toolchain ==="
    CARGO_BIN="$HOME/.cargo/bin/cargo"
    if [[ -x "$CARGO_BIN" ]]; then
      ok "cargo already installed: $("$CARGO_BIN" --version)"
    else
      log "Installing Rust via rustup (needed to build tools from source)..."
      if curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs |
        sh -s -- -y --no-modify-path --quiet; then
        ok "Rust installed: $("$CARGO_BIN" --version)"
      else
        warn "rustup install failed — Rust tools will be skipped, not downloaded."
      fi
    fi

    if [[ -x "$CARGO_BIN" ]]; then
      export PATH="$HOME/.cargo/bin:$PATH"

      # cargo needs a C linker (cc/gcc) even for pure-Rust crates.
      if ! command -v cc &>/dev/null && ! command -v gcc &>/dev/null; then
        log "C linker not found — installing build-essential..."
        if command -v apt-get &>/dev/null; then
          sudo apt-get install -y build-essential &&
            ok "build-essential installed" ||
            warn "Could not install build-essential — cargo builds will fail (non-fatal)."
        elif command -v brew &>/dev/null; then
          brew install gcc && ok "gcc installed" ||
            warn "Could not install gcc — cargo builds will fail (non-fatal)."
        else
          warn "No C linker found and no known package manager to install one — cargo builds will fail."
          warn "Install gcc/build-essential manually, then re-run install.sh --cargo."
        fi
      fi

      warn "Cargo mode: all Rust tools will compile from source — this may take a while."
    else
      err "--cargo was requested but no working cargo is available — Rust tools will be skipped, not downloaded."
    fi
  fi

  log "=== Core shell stack ==="

  # dest | crate | repo | os | arch | glob | bin
  CORE_TOOLS=(
    "starship|starship|starship/starship|linux|x86_64|starship-x86_64-unknown-linux-musl.tar.gz|-"
    "starship|starship|starship/starship|linux|aarch64|starship-aarch64-unknown-linux-musl.tar.gz|-"
    "starship|starship|starship/starship|darwin|*|starship-*-apple-darwin.tar.gz|-"

    "zellij|zellij|zellij-org/zellij|linux|x86_64|zellij-x86_64-unknown-linux-musl.tar.gz|-"
    "zellij|zellij|zellij-org/zellij|linux|aarch64|zellij-aarch64-unknown-linux-musl.tar.gz|-"
    "zellij|zellij|zellij-org/zellij|darwin|*|zellij-*-apple-darwin.tar.gz|-"
  )
  for t in "${CORE_TOOLS[@]}"; do install_tool "$t"; done

  # Neovim — tarball release (includes runtime + bundled treesitter parsers).
  # AppImage was dropped: it omits the runtime directory and requires FUSE
  # which is unavailable in most WSL2 kernels.
  log "Checking nvim..."
  latest=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
    "${GITHUB_AUTH[@]}" "https://api.github.com/repos/neovim/neovim/releases/latest" |
    grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
  if [[ -z "$latest" ]]; then
    warn "Could not determine nvim latest version — skipping."
  else
    installed=$(get_installed_version "nvim")
    if [[ "$installed" != "$latest" || "$FORCE_UPDATE" == true || ! -f "$HOME/.local/share/nvim/runtime/syntax/syntax.vim" ]]; then
      log "Downloading nvim ${latest}..."
      tmpdir=$(mktemp -d)
      if [[ "$OS" == "linux" && "$ARCH" == "x86_64" ]]; then
        NVIM_ASSET="nvim-linux-x86_64.tar.gz"
      elif [[ "$OS" == "linux" && "$ARCH" == "aarch64" ]]; then
        NVIM_ASSET="nvim-linux-arm64.tar.gz"
      elif [[ "$OS" == "darwin" && "$ARCH" == "aarch64" ]]; then
        NVIM_ASSET="nvim-macos-arm64.tar.gz"
      else
        NVIM_ASSET="nvim-macos-x86_64.tar.gz"
      fi
      curl -fL --connect-timeout 30 --max-time 600 --retry 2 \
        "https://github.com/neovim/neovim/releases/download/${latest}/${NVIM_ASSET}" \
        -o "$tmpdir/nvim.tar.gz"
      tar -xzf "$tmpdir/nvim.tar.gz" -C "$tmpdir"
      NVIM_DIR=$(find "$tmpdir" -maxdepth 1 -name "nvim-*" -type d | head -1)
      install -m 755 "$NVIM_DIR/bin/nvim" "$BIN_DIR/nvim"
      # Runtime: syntax files, treesitter queries, ftplugins, etc.
      mkdir -p "$HOME/.local/share/nvim/runtime"
      cp -r "$NVIM_DIR/share/nvim/runtime/." "$HOME/.local/share/nvim/runtime/"
      # Bundled treesitter parsers (present since nvim 0.10)
      if [[ -d "$NVIM_DIR/lib/nvim" ]]; then
        mkdir -p "$HOME/.local/lib/nvim"
        cp -r "$NVIM_DIR/lib/nvim/." "$HOME/.local/lib/nvim/"
      fi
      rm -rf "$tmpdir"
      set_installed_version "nvim" "$latest"
      ok "nvim installed at ${latest}"
    else
      ok "nvim already at ${latest}"
    fi
  fi

  log "=== CLI tools ==="

  # dest | crate | repo | os | arch | glob | bin
  CLI_TOOLS=(
    "bat|bat|sharkdp/bat|linux|x86_64|bat-*-x86_64*linux*musl*.tar.gz|-"
    "bat|bat|sharkdp/bat|linux|aarch64|bat-*-aarch64*linux*musl*.tar.gz|-"
    "bat|bat|sharkdp/bat|darwin|*|bat-*-*apple*darwin*.tar.gz|-"

    "fd|fd-find|sharkdp/fd|linux|x86_64|fd-*-x86_64*linux*musl*.tar.gz|-"
    "fd|fd-find|sharkdp/fd|linux|aarch64|fd-*-aarch64*linux*musl*.tar.gz|-"
    "fd|fd-find|sharkdp/fd|darwin|*|fd-*-*apple*darwin*.tar.gz|-"

    "rg|ripgrep|BurntSushi/ripgrep|linux|x86_64|ripgrep-*-x86_64*linux*musl*.tar.gz|rg"
    "rg|ripgrep|BurntSushi/ripgrep|linux|aarch64|ripgrep-*-aarch64*linux*.tar.gz|rg"
    "rg|ripgrep|BurntSushi/ripgrep|darwin|*|ripgrep-*-*apple*darwin*.tar.gz|rg"

    "rga|ripgrep_all|phiresky/ripgrep-all|linux|x86_64|ripgrep_all-*-x86_64*linux*musl*.tar.gz|rga"
    "rga|ripgrep_all|phiresky/ripgrep-all|darwin|*|ripgrep_all-*-*apple*darwin*.tar.gz|rga"

    "eza|eza|eza-community/eza|linux|x86_64|eza_x86_64*linux*musl*.tar.gz|-"
    "eza|eza|eza-community/eza|linux|aarch64|eza_aarch64*linux*musl*.tar.gz|-"
    "eza|eza|eza-community/eza|darwin|*|eza_*apple*darwin*.tar.gz|-"

    "fzf|-|junegunn/fzf|linux|x86_64|fzf-*-linux_amd64.tar.gz|-"
    "fzf|-|junegunn/fzf|linux|aarch64|fzf-*-linux_arm64.tar.gz|-"
    "fzf|-|junegunn/fzf|darwin|x86_64|fzf-*-darwin_amd64.tar.gz|-"
    "fzf|-|junegunn/fzf|darwin|aarch64|fzf-*-darwin_arm64.tar.gz|-"

    "zoxide|zoxide|ajeetdsouza/zoxide|linux|x86_64|zoxide-*-x86_64*linux*musl*.tar.gz|-"
    "zoxide|zoxide|ajeetdsouza/zoxide|linux|aarch64|zoxide-*-aarch64*linux*musl*.tar.gz|-"
    "zoxide|zoxide|ajeetdsouza/zoxide|darwin|*|zoxide-*-*apple*darwin*.tar.gz|-"

    # ruff: Python linter/formatter (+ built-in `ruff server` LSP). Standalone
    # binary, so it works without pip — Mason's ruff is pip-based and can't
    # install here. nvim points its ruff server at this via mason=false
    # (see nvim plugins/lsp-servers.lua).
    "ruff|ruff|astral-sh/ruff|linux|x86_64|ruff-x86_64-unknown-linux-musl.tar.gz|-"
    "ruff|ruff|astral-sh/ruff|linux|aarch64|ruff-aarch64-unknown-linux-musl.tar.gz|-"
    "ruff|ruff|astral-sh/ruff|darwin|x86_64|ruff-x86_64-apple-darwin.tar.gz|-"
    "ruff|ruff|astral-sh/ruff|darwin|aarch64|ruff-aarch64-apple-darwin.tar.gz|-"

    # uv: Python package/tool manager. Not needed for anything above — it
    # exists solely to `uv tool install claude-swap` (see install_claude_swap
    # below, called once this loop has downloaded uv into $BIN_DIR).
    "uv|-|astral-sh/uv|linux|x86_64|uv-x86_64-unknown-linux-musl.tar.gz|-"
    "uv|-|astral-sh/uv|linux|aarch64|uv-aarch64-unknown-linux-musl.tar.gz|-"
    "uv|-|astral-sh/uv|darwin|x86_64|uv-x86_64-apple-darwin.tar.gz|-"
    "uv|-|astral-sh/uv|darwin|aarch64|uv-aarch64-apple-darwin.tar.gz|-"

    "lazygit|-|jesseduffield/lazygit|linux|x86_64|lazygit_*_Linux_x86_64.tar.gz|-"
    "lazygit|-|jesseduffield/lazygit|linux|aarch64|lazygit_*_Linux_arm64.tar.gz|-"
    "lazygit|-|jesseduffield/lazygit|darwin|*|lazygit_*_Darwin_*.tar.gz|-"

    "serpl|yassinebridi/serpl|linux|x86_64|serpl-*-linux-x86_64.tar.gz"
    "serpl|yassinebridi/serpl|linux|aarch64|serpl-*-linux-arm64.tar.gz"
    "serpl|yassinebridi/serpl|darwin|x86_64|serpl-*-macos-x86_64.tar.gz"
    "serpl|yassinebridi/serpl|darwin|aarch64|serpl-*-macos-arm64.tar.gz"

    "gping|gping|orf/gping|linux|x86_64|gping-Linux-musl-x86_64.tar.gz|-"
    "gping|gping|orf/gping|linux|aarch64|gping-Linux-musl-arm64.tar.gz|-"
    "gping|gping|orf/gping|darwin|x86_64|gping-macOS-x86_64.tar.gz|-"
    "gping|gping|orf/gping|darwin|aarch64|gping-macOS-arm64.tar.gz|-"

    "trip|trippy|fujiapple852/trippy|linux|x86_64|trippy-*-x86_64-unknown-linux-musl.tar.gz|trip"
    "trip|trippy|fujiapple852/trippy|linux|aarch64|trippy-*-aarch64-unknown-linux-musl.tar.gz|trip"
    "trip|trippy|fujiapple852/trippy|darwin|x86_64|trippy-*-x86_64-apple-darwin.tar.gz|trip"
    "trip|trippy|fujiapple852/trippy|darwin|aarch64|trippy-*-aarch64-apple-darwin.tar.gz|trip"

    "tldr|tealdeer|tealdeer-rs/tealdeer|linux|x86_64|tealdeer-linux-x86_64-musl|-"
    "tldr|tealdeer|tealdeer-rs/tealdeer|linux|aarch64|tealdeer-linux-aarch64-musl|-"
    "tldr|tealdeer|tealdeer-rs/tealdeer|darwin|*|tealdeer-macos|-"

    "tspin|tailspin|bensadeh/tailspin|linux|x86_64|tailspin-x86_64-unknown-linux-musl.tar.gz|-"
    "tspin|tailspin|bensadeh/tailspin|linux|aarch64|tailspin-aarch64-unknown-linux-musl.tar.gz|-"
    "tspin|tailspin|bensadeh/tailspin|darwin|*|tailspin-*-apple-darwin.tar.gz|-"

    "choose|choose|theryangeary/choose|linux|x86_64|choose-x86_64-unknown-linux-musl|-"
    "choose|choose|theryangeary/choose|darwin|*|choose-*-apple-darwin|-"

    "difft|difftastic|Wilfred/difftastic|linux|x86_64|difft-x86_64-unknown-linux-gnu.tar.gz|-"
    "difft|difftastic|Wilfred/difftastic|linux|aarch64|difft-aarch64-unknown-linux-gnu.tar.gz|-"
    "difft|difftastic|Wilfred/difftastic|darwin|x86_64|difft-x86_64-apple-darwin.tar.gz|-"
    "difft|difftastic|Wilfred/difftastic|darwin|aarch64|difft-aarch64-apple-darwin.tar.gz|-"

    "atuin|atuin|atuinsh/atuin|linux|x86_64|atuin-x86_64-unknown-linux-musl.tar.gz|-"
    "atuin|atuin|atuinsh/atuin|linux|aarch64|atuin-aarch64-unknown-linux-musl.tar.gz|-"
    "atuin|atuin|atuinsh/atuin|darwin|*|atuin-*-apple-darwin.tar.gz|-"

    "procs|procs|dalance/procs|linux|x86_64|procs-v*-x86_64*linux*.zip|-"
    "procs|procs|dalance/procs|darwin|*|procs-v*-*apple*darwin*.zip|-"

    "sd|sd|chmln/sd|linux|x86_64|sd-v*-x86_64*linux*musl*.tar.gz|-"
    "sd|sd|chmln/sd|darwin|*|sd-v*-*apple*darwin*.tar.gz|-"

    "viddy|-|sachaos/viddy|linux|x86_64|viddy-*-linux-x86_64.tar.gz|-"
    "viddy|-|sachaos/viddy|linux|aarch64|viddy-*-linux-arm64.tar.gz|-"
    "viddy|-|sachaos/viddy|darwin|x86_64|viddy-*-macos-x86_64.tar.gz|-"
    "viddy|-|sachaos/viddy|darwin|aarch64|viddy-*-macos-arm64.tar.gz|-"

    "ouch|ouch|ouch-org/ouch|linux|x86_64|ouch-x86_64-unknown-linux-musl.tar.gz|-"
    "ouch|ouch|ouch-org/ouch|linux|aarch64|ouch-aarch64-unknown-linux-musl.tar.gz|-"
    "ouch|ouch|ouch-org/ouch|darwin|*|ouch-*-apple-darwin.tar.gz|-"

    "presenterm|presenterm|mfontanini/presenterm|linux|x86_64|presenterm-*-x86_64*linux*musl*.tar.gz|-"
    "presenterm|presenterm|mfontanini/presenterm|darwin|*|presenterm-*-*apple*darwin*.tar.gz|-"

    "asciinema|-|asciinema/asciinema|linux|x86_64|asciinema-x86_64-unknown-linux-musl|-"
    "asciinema|-|asciinema/asciinema|linux|aarch64|asciinema-aarch64-unknown-linux-gnu|-"
    "asciinema|-|asciinema/asciinema|darwin|x86_64|asciinema-x86_64-apple-darwin|-"
    "asciinema|-|asciinema/asciinema|darwin|aarch64|asciinema-aarch64-apple-darwin|-"

    "btm|bottom|ClementTsang/bottom|linux|x86_64|bottom_x86_64-unknown-linux-musl.tar.gz|btm"
    "btm|bottom|ClementTsang/bottom|linux|aarch64|bottom_aarch64-unknown-linux-musl.tar.gz|btm"
    "btm|bottom|ClementTsang/bottom|darwin|*|bottom_*-apple-darwin.tar.gz|btm"

    "carapace|-|carapace-sh/carapace-bin|linux|x86_64|carapace-bin_*_linux_amd64.tar.gz|carapace"
    "carapace|-|carapace-sh/carapace-bin|linux|aarch64|carapace-bin_*_linux_arm64.tar.gz|carapace"
    "carapace|-|carapace-sh/carapace-bin|darwin|x86_64|carapace-bin_*_darwin_amd64.tar.gz|carapace"
    "carapace|-|carapace-sh/carapace-bin|darwin|aarch64|carapace-bin_*_darwin_arm64.tar.gz|carapace"

    "glow|-|charmbracelet/glow|linux|x86_64|glow_*_linux_x86_64.tar.gz|glow"
    "glow|-|charmbracelet/glow|linux|aarch64|glow_*_linux_arm64.tar.gz|glow"
    "glow|-|charmbracelet/glow|darwin|*|glow_*_darwin_*.tar.gz|glow"

    "7zz|7zz|ip7z/7zip|linux|x86_64|7z*-linux-x64.tar.xz|7zz"
    "7zz|7zz|ip7z/7zip|linux|aarch64|7z*-linux-arm.tar.xz|7zz"
    "7zz|7zz|ip7z/7zip|darwin|*|7z*-mac.tar.xz|7zz"

    "jq|-|jqlang/jq|linux|x86_64|jq-linux-amd64|jq"
    "jq|-|jqlang/jq|linux|aarch64|jq-linux-arm64|jq"
    "jq|-|jqlang/jq|darwin|x86_64|jq-macos-amd64|jq"
    "jq|-|jqlang/jq|darwin|aarch64|jq-macos-arm64|jq"

    "tree-sitter-cli|-|tree-sitter/tree-sitter|linux|x86_64|tree-sitter-cli-linux-x64|tree-sitter"
    "tree-sitter-cli|-|tree-sitter/tree-sitter|linux|aarch64|tree-sitter-cli-linux-arm64|tree-sitter"
    "tree-sitter-cli|-|tree-sitter/tree-sitter|darwin|x86_64|tree-sitter-cli-macos-x64|tree-sitter"
    "tree-sitter-cli|-|tree-sitter/tree-sitter|darwin|aarch64|tree-sitte-clir-macos-arm64|tree-sitter"
  )
  for t in "${CLI_TOOLS[@]}"; do install_tool "$t"; done

  # yazi (includes ya companion binary) — two binaries from the same archive
  # Always use binary releases: crates.io requires a yazi-build workaround that's unreliable
  if [[ "$OS" == "linux" && "$ARCH" == "x86_64" ]]; then
    download_release "sxyazi/yazi" "yazi-x86_64-unknown-linux-musl.zip" "yazi" "yazi"
    log "Extracting ya companion binary..."
    tmpdir=$(mktemp -d)
    latest_yazi=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
      "${GITHUB_AUTH[@]}" "https://api.github.com/repos/sxyazi/yazi/releases/latest" |
      grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
    if [[ -z "$latest_yazi" ]]; then
      warn "Could not fetch latest version for sxyazi/yazi — skipping ya companion binary."
    elif ! curl -sfL --connect-timeout 30 --max-time 600 --retry 2 \
      "https://github.com/sxyazi/yazi/releases/download/${latest_yazi}/yazi-x86_64-unknown-linux-musl.zip" \
      -o "$tmpdir/yazi.zip"; then
      warn "Download failed for ya companion binary — skipping."
    elif ! unzip -q "$tmpdir/yazi.zip" -d "$tmpdir"; then
      warn "Could not extract ya companion binary archive — skipping."
    else
      ya_bin=$(find "$tmpdir" -name "ya" | head -1)
      [[ -f "$ya_bin" ]] && install -m 755 "$ya_bin" "$BIN_DIR/ya"
    fi
    rm -rf "$tmpdir"
  elif [[ "$OS" == "linux" && "$ARCH" == "aarch64" ]]; then
    download_release "sxyazi/yazi" "yazi-aarch64-unknown-linux-musl.zip" "yazi" "yazi"
  elif [[ "$OS" == "darwin" ]]; then
    download_release "sxyazi/yazi" "yazi-*-apple-darwin.zip" "yazi" "yazi"
  fi

  # mosh — no pre-built release binaries, use system package manager
  if ! command -v mosh &>/dev/null; then
    log "Installing mosh via system package manager..."
    if command -v apt-get &>/dev/null; then
      sudo apt-get install -y mosh 2>/dev/null && ok "mosh installed" || warn "mosh install failed (non-fatal)"
    elif command -v brew &>/dev/null; then
      brew install mosh && ok "mosh installed"
    else
      warn "mosh: please install manually (e.g. apt install mosh)"
    fi
  fi

  # ── Post-download: bat theme cache ────────────────────────────────────────
  log "=== Post-download setup ==="

  if [[ -f "$BIN_DIR/bat" ]]; then
    log "Installing Catppuccin bat theme..."
    BAT_CONFIG_DIR="$HOME/.config/bat"
    mkdir -p "$BAT_CONFIG_DIR/themes"
    if [[ ! -f "$BAT_CONFIG_DIR/themes/Catppuccin Mocha.tmTheme" ]]; then
      curl -sfL \
        "https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme" \
        -o "$BAT_CONFIG_DIR/themes/Catppuccin Mocha.tmTheme"
    fi
    "$BIN_DIR/bat" cache --build &>/dev/null && ok "bat theme cache built"
  fi

  # ── eza Catppuccin theme ─────────────────────────────────────────────────────
  # Official catppuccin/eza port, mauve accent (matches Starship's directory
  # segment and Zellij's active-tab color elsewhere in this repo). eza reads
  # $EZA_CONFIG_DIR/theme.yml (EZA_CONFIG_DIR set in zsh/.zshenv).
  EZA_THEME_DIR="$HOME/.config/eza"
  mkdir -p "$EZA_THEME_DIR"
  if [[ ! -f "$EZA_THEME_DIR/theme.yml" ]]; then
    log "Downloading eza Catppuccin Mocha (mauve) theme..."
    curl -sfL --connect-timeout 15 \
      "https://raw.githubusercontent.com/catppuccin/eza/main/themes/mocha/catppuccin-mocha-mauve.yml" \
      -o "$EZA_THEME_DIR/theme.yml" &&
      ok "eza theme downloaded" ||
      warn "eza theme download failed — source manually from catppuccin/eza"
  fi

  # ── zsh-syntax-highlighting Catppuccin theme ────────────────────────────────
  # Official catppuccin/zsh-syntax-highlighting port — sets ZSH_HIGHLIGHT_STYLES,
  # sourced by .zshrc *before* the plugin itself (see zsh/.zshrc), same
  # "before you activate zsh-syntax-highlighting" requirement the upstream
  # theme file's own header documents.
  ZSH_THEME_DIR="$HOME/.config/zsh/themes"
  mkdir -p "$ZSH_THEME_DIR"
  if [[ ! -f "$ZSH_THEME_DIR/catppuccin_mocha-zsh-syntax-highlighting.zsh" ]]; then
    log "Downloading zsh-syntax-highlighting Catppuccin Mocha theme..."
    curl -sfL --connect-timeout 15 \
      "https://raw.githubusercontent.com/catppuccin/zsh-syntax-highlighting/main/themes/catppuccin_mocha-zsh-syntax-highlighting.zsh" \
      -o "$ZSH_THEME_DIR/catppuccin_mocha-zsh-syntax-highlighting.zsh" &&
      ok "zsh-syntax-highlighting theme downloaded" ||
      warn "zsh-syntax-highlighting theme download failed — source manually from catppuccin/zsh-syntax-highlighting"
  fi

  # ── Claude Code stack — gated behind --claude or --full ────────────────────
  # Claude Code itself, Node.js (needed here only to npm-install ccstatusline —
  # Mason's npm-based Neovim LSP servers are a separate consumer, gated on
  # FULL_INSTALL directly below via the marker file, and FULL_INSTALL implies
  # WANT_CLAUDE_STACK so Node is still there when those LSPs need it),
  # ccstatusline, and claude-swap are all useless without Claude Code, so none
  # of them install unless this run wants the stack. This is also why "is node
  # on PATH" can't be nvim's --full signal (see FULL_INSTALL_MARKER below) —
  # --claude alone would make that read true without --full being passed.
  if [[ "$WANT_CLAUDE_STACK" == true ]]; then
    install_node
    install_claude
    install_ccstatusline
    install_claude_swap
  else
    log "Skipping Claude Code/node/ccstatusline/claude-swap (use --claude or --full to include them)"
  fi

  # ── PowerShell (self-contained pwsh + bundled .NET; unblocks powershell_es LSP)
  # Opt-in via --full — nothing else on this machine needs pwsh, so "is pwsh on
  # PATH" stays a valid --full signal on its own; nvim's lsp-servers.lua checks
  # `vim.fn.executable("pwsh")` directly rather than needing the marker file
  # below.
  if [[ "$FULL_INSTALL" == true ]]; then
    install_powershell
  else
    log "Skipping PowerShell install (use --full to include it)"
  fi

  # ── Full-install marker for Neovim's Mason-managed LSPs ────────────────────
  # nvim's lua/config/lazy.lua and lua/plugins/lsp-servers.lua read this file's
  # presence to decide whether to enable the Node-dependent-but-not-pwsh-
  # dependent servers that Mason would otherwise auto-install on first buffer
  # open: html, cssls, emmet_language_server, bashls, pyright, and the whole
  # lang.php extra (intelephense/phpactor/php-cs-fixer/phpcs) — together
  # ~460MB of Mason packages that only make sense on a full IDE workstation.
  # Written/removed every run (not just when changed) so re-running install.sh
  # without --full after previously using it correctly downgrades nvim's LSP
  # config on next launch — it does NOT retroactively uninstall whatever
  # Mason already downloaded; that's a manual `:Mason` / `:MasonUninstall`
  # cleanup step (Mason has no "uninstall what's no longer declared" mode).
  FULL_INSTALL_MARKER="$HOME/.local/state/dotfiles/full-install"
  mkdir -p "$(dirname "$FULL_INSTALL_MARKER")"
  if [[ "$FULL_INSTALL" == true ]]; then
    touch "$FULL_INSTALL_MARKER"
  else
    rm -f "$FULL_INSTALL_MARKER"
  fi

fi # end --link / skip downloads

# ── Package list (shared by deploy and remove) ────────────────────────────────
PACKAGES=(
  bin bash zsh starship zellij nvim
  git ripgrep bat yazi atuin lazygit tealdeer ssh alacritty claude ccstatusline
)

# ── Remove deployed symlinks ──────────────────────────────────────────────────
remove_package() {
  local pkg_dir="$DOTFILES/$1"
  [[ -d "$pkg_dir" ]] || return
  while IFS= read -r -d '' src; do
    local rel="${src#$pkg_dir/}"
    local target="$HOME/$rel"
    if [[ -L "$target" ]]; then
      rm "$target"
      ok "Removed $target"
    fi
  done < <(find "$pkg_dir" -type f -print0 2>/dev/null)
}

if [[ "$DO_REMOVE" == true ]]; then
  log "=== Removing deployed symlinks ==="
  for pkg in "${PACKAGES[@]}"; do
    remove_package "$pkg"
  done
  ok "Done — symlinks removed. Binaries in $BIN_DIR are untouched."
  exit 0
fi

# ── Prune stale symlinks ───────────────────────────────────────────────────────
# Config files get renamed or removed from the repo over time. Their old
# symlinks in $HOME are left dangling — link_package only creates/updates
# symlinks for files that currently exist, it never notices ones that no
# longer have a source. Sweep $HOME for any symlink pointing into $DOTFILES
# whose target no longer exists and remove it before (re)linking.
prune_stale_symlinks() {
  log "Checking for stale dotfiles symlinks..."
  local pruned=0
  while IFS= read -r -d '' link; do
    local target
    target=$(readlink "$link")
    [[ "$target" == "$DOTFILES"/* ]] || continue
    rm "$link"
    ok "Removed stale symlink: $link -> $target"
    ((pruned++)) || true
  done < <(find "$HOME" \
    \( -path "$HOME/.cache" -o -path "$HOME/.cargo" -o -path "$HOME/.rustup" \
    -o -path "$HOME/.npm" -o -path "$HOME/.local/share/nvim" \
    -o -path "$DOTFILES" \) -prune -o \
    -xtype l -print0 2>/dev/null)
  [[ "$pruned" -eq 0 ]] && ok "No stale symlinks found" || ok "Pruned ${pruned} stale symlink(s)"
}
prune_stale_symlinks

# ── Deploy configs ────────────────────────────────────────────────────────────
[[ "$USE_COPY" == true ]] && log "=== Copying configs ===" || log "=== Linking configs ==="

BACKUP_SUFFIX=".bak.$(date +%Y%m%d%H%M%S)"

link_package() {
  local pkg_dir="$DOTFILES/$1"
  if [[ ! -d "$pkg_dir" ]]; then
    warn "Package not found: $1 (skipping)"
    return
  fi
  # Load ignore patterns from .linkignore in the package root (one glob per line, # = comment)
  local -a ignore_patterns=()
  local ignore_file="$pkg_dir/.linkignore"
  if [[ -f "$ignore_file" ]]; then
    while IFS= read -r pattern; do
      [[ -z "$pattern" || "$pattern" == \#* ]] && continue
      ignore_patterns+=("$pattern")
    done <"$ignore_file"
  fi
  while IFS= read -r -d '' src; do
    local rel="${src#$pkg_dir/}"
    # Skip .linkignore itself and files matching any ignore pattern
    local skip=false
    [[ "$rel" == ".linkignore" ]] && skip=true
    for pat in "${ignore_patterns[@]}"; do
      # shellcheck disable=SC2254
      case "$rel" in $pat)
        skip=true
        break
        ;;
      esac
    done
    [[ "$skip" == true ]] && continue
    local target="$HOME/$rel"
    mkdir -p "$(dirname "$target")"
    if [[ -e "$target" && ! -L "$target" ]]; then
      warn "Backing up: $target → ${target}${BACKUP_SUFFIX}"
      mv "$target" "${target}${BACKUP_SUFFIX}"
    fi
    if [[ "$USE_COPY" == true ]]; then
      cp "$src" "$target"
    else
      ln -sf "$src" "$target"
    fi
  done < <(find "$pkg_dir" -type f -print0 2>/dev/null)
  [[ "$USE_COPY" == true ]] && ok "Copied $1" || ok "Linked $1"
}

for pkg in "${PACKAGES[@]}"; do
  link_package "$pkg"
done

# ── Register the "homepath" git filter ────────────────────────────────────────
# zjstatus's command_*_command paths and Neovim's g.clipboard exec path must be
# real absolute paths — zjstatus runs its WASM plugin commands directly with no
# shell (no ~ or $HOME expansion), and Neovim's clipboard exec is likewise not
# shell-expanded. zellij/.config/zellij/config.kdl and
# nvim/.config/nvim/lua/config/autocmds.lua store a __DOTFILES_HOME__
# placeholder instead of a real path; git's clean/smudge filters (defined in
# git-filters/*.sh, wired up via .gitattributes) expand it to this machine's
# $HOME on checkout and fold it back to the placeholder before anything is
# staged — so switching machines/usernames never shows up as a diff to commit.
# Filter *commands* live in local git config (not versioned), so they must be
# registered on every clone/run; the checkout below re-smudges the working
# tree in case the filter wasn't registered yet when these files were last
# checked out (e.g. right after a fresh clone).
log "=== Registering homepath git filter ==="
# git execs these directly (no shell wrapper), so the mode bit must be +x or
# every clean/smudge invocation fails — same pitfall as the zjstatus/clipboard
# scripts noted above. Enforce it defensively in case a checkout ever drops it.
chmod +x "$DOTFILES/git-filters/homepath-clean.sh" "$DOTFILES/git-filters/homepath-smudge.sh"
git -C "$DOTFILES" config filter.homepath.clean "$DOTFILES/git-filters/homepath-clean.sh"
git -C "$DOTFILES" config filter.homepath.smudge "$DOTFILES/git-filters/homepath-smudge.sh"
git -C "$DOTFILES" config filter.homepath.required true
# `checkout-index -f` still skips re-smudging when the working-tree file's
# stat already matches the index (e.g. right after a fresh clone left the raw
# placeholder in place because the filter wasn't registered yet) — `-f` only
# forces overwriting, it doesn't bypass that freshness check. Removing the
# file first guarantees a real rewrite, so the filter always actually runs.
rm -f "$DOTFILES/zellij/.config/zellij/config.kdl" \
  "$DOTFILES/nvim/.config/nvim/lua/config/autocmds.lua"
git -C "$DOTFILES" checkout-index -f -- \
  zellij/.config/zellij/config.kdl \
  nvim/.config/nvim/lua/config/autocmds.lua
# Verify the placeholder actually got replaced — the filter has failed
# silently before (non-executable script, stat-cache skip above), and a
# leftover __DOTFILES_HOME__ breaks zjstatus/Neovim clipboard with no visible
# error at runtime. Fail loudly here instead of discovering it later.
if grep -q '__DOTFILES_HOME__' \
  "$DOTFILES/zellij/.config/zellij/config.kdl" \
  "$DOTFILES/nvim/.config/nvim/lua/config/autocmds.lua"; then
  err "homepath filter did not expand __DOTFILES_HOME__ — check git-filters/*.sh are executable and filter.homepath.* is registered"
  exit 1
fi
ok "Registered homepath git filter"

# ── Neovim: headless plugin install ──────────────────────────────────────────
if [[ -f "$LOCAL_BIN/nvim" ]] || command -v nvim &>/dev/null; then
  NVIM_CMD="${LOCAL_BIN}/nvim"
  [[ -f "$NVIM_CMD" ]] || NVIM_CMD="nvim"
  if [[ ! -f "$HOME/.local/share/nvim/runtime/syntax/syntax.vim" ]]; then
    warn "nvim runtime missing — skipping headless plugin install. Run install.sh again after nvim downloads."
  else
    log "Installing Neovim plugins (headless — this may take a minute)..."
    VIMRUNTIME="$HOME/.local/share/nvim/runtime" \
      "$NVIM_CMD" --headless '+Lazy! sync' +qa 2>&1 | tail -5 ||
      warn "nvim plugins: some issues encountered — run :Lazy sync manually"
    ok "Neovim plugins installed"
  fi
fi

# ── Generate shell init scripts ───────────────────────────────────────────────
log "=== Generating shell init scripts ==="

if [[ ! -f "$HOME/.local/share/atuin/init.zsh" ]] && { command -v atuin &>/dev/null || [[ -f "$LOCAL_BIN/atuin" ]]; }; then
  ATUIN="${LOCAL_BIN}/atuin"
  [[ -f "$ATUIN" ]] || ATUIN="atuin"
  "$ATUIN" init zsh --disable-up-arrow >"$HOME/.local/share/atuin/init.zsh" 2>/dev/null && ok "atuin init generated"
fi

if [[ ! -f "$HOME/.cache/starship/init.zsh" ]] && { command -v starship &>/dev/null || [[ -f "$LOCAL_BIN/starship" ]]; }; then
  STARSHIP="${LOCAL_BIN}/starship"
  [[ -f "$STARSHIP" ]] || STARSHIP="starship"
  mkdir -p "$HOME/.cache/starship"
  "$STARSHIP" init zsh >"$HOME/.cache/starship/init.zsh" 2>/dev/null && ok "starship init generated"
fi

if [[ ! -f "$HOME/.local/share/zoxide/init.zsh" ]] && { command -v zoxide &>/dev/null || [[ -f "$LOCAL_BIN/zoxide" ]]; }; then
  ZOXIDE="${LOCAL_BIN}/zoxide"
  [[ -f "$ZOXIDE" ]] || ZOXIDE="zoxide"
  mkdir -p "$HOME/.local/share/zoxide"
  "$ZOXIDE" init zsh >"$HOME/.local/share/zoxide/init.zsh" 2>/dev/null && ok "zoxide init generated"
fi

if [[ ! -f "$HOME/.cache/carapace/init.zsh" ]] && { command -v carapace &>/dev/null || [[ -f "$LOCAL_BIN/carapace" ]]; }; then
  CARAPACE="${LOCAL_BIN}/carapace"
  [[ -f "$CARAPACE" ]] || CARAPACE="carapace"
  "$CARAPACE" _carapace zsh >"$HOME/.cache/carapace/init.zsh" 2>/dev/null && ok "carapace init generated"
fi

# ── Yazi: packages (flavors + plugins) ────────────────────────────────────────
YAZI_PACKAGES=(
  yazi-rs/flavors:catppuccin-mocha
  yazi-rs/plugins:full-border
  yazi-rs/plugins:git
  yazi-rs/plugins:piper
  imsi32/yatline
  imsi32/yatline-catppuccin
  imsi32/yatline-githead
  ndtoan96/ouch
  Rolv-Apneseth/starship
)
if command -v ya &>/dev/null || [[ -f "$LOCAL_BIN/ya" ]]; then
  YA="${LOCAL_BIN}/ya"
  [[ -f "$YA" ]] || YA="ya"
  log "Adding yazi packages..."
  for pkg in "${YAZI_PACKAGES[@]}"; do
    "$YA" pkg add "$pkg" 2>/dev/null || true
    ok "yazi: queued ${pkg}"
  done
  if "$YA" pkg install 2>/dev/null; then
    ok "yazi packages installed"
  else
    warn "yazi pkg install failed — run 'ya pkg install' manually"
  fi
fi

# ── Zellij: plugins (downloaded once to a local file, no network needed after) ─
# zellij/.config/zellij/config.kdl loads these via file:~/.local/share/zellij/
# plugins/<name> — Zellij's own plugin dir, not ~/.local/bin (these are never
# invoked directly, so they don't belong on PATH). Using a local file instead
# of https:// matters because this layout runs on every new shell via
# zellij_autostart, so a live fetch (or a dead pinned tag) would block every
# new terminal, not just one session. Versions here must match config.kdl;
# update both together when bumping one.
ZELLIJ_PLUGIN_DIR="${SHARE_DIR}/zellij/plugins"
mkdir -p "$ZELLIJ_PLUGIN_DIR"
ZELLIJ_PLUGINS=(
  "zellij-autolock.wasm|fresh2dev/zellij-autolock|0.2.2"
  "zjstatus.wasm|dj95/zjstatus|v0.24.0"
  "zellij-newtab-plus.wasm|AlexZasorin/zellij-newtab-plus|v0.6.0"
  "zjstatus-hints.wasm|myah-mitchell/zjstatus-hints|v0.4.0"
)
log "=== Zellij plugins ==="
for entry in "${ZELLIJ_PLUGINS[@]}"; do
  IFS='|' read -r dest repo tag <<<"$entry"
  installed=$(get_installed_version "$dest")
  if [[ "$installed" == "$tag" && "$FORCE_UPDATE" == false ]]; then
    ok "${dest} already at ${tag}"
    continue
  fi
  log "Downloading ${dest} ${tag}..."
  if curl -fL --connect-timeout 30 --max-time 120 --retry 2 \
    "https://github.com/${repo}/releases/download/${tag}/${dest}" \
    -o "${ZELLIJ_PLUGIN_DIR}/${dest}"; then
    set_installed_version "$dest" "$tag"
    ok "${dest} installed at ${tag}"
  else
    warn "Download failed for ${dest} — zjstatus/autolock won't load until this succeeds (re-run install.sh)"
  fi
done

# ── Zellij: pre-approve plugin permissions ────────────────────────────────────
# Each plugin's request_permission() call requires one-time user approval via a
# y/n prompt rendered inside its own pane. zjstatus and autolock both live in
# size=1 borderless panes that aren't the pane focused on startup, so that
# prompt is easy to never see — the plugin then sits inert forever, looking
# "broken" with no visible error. Seeding the grant here avoids that entirely.
# Permissions below match each plugin's own request_permission() call (checked
# against source at time of writing — re-check if bumping versions above).
# Append-only: never overwrites grants for other plugins the user has approved.
#
# Keyed by the *deployed* ~/.local/share path, not $ZELLIJ_PLUGIN_DIR (the repo
# source dir) — Zellij's permission cache key is exactly what config.kdl's
# file: location shell-expands to (no symlink resolution), which is always
# the stowed ~/.local/share/zellij/plugins/<name> path.
ZELLIJ_PLUGIN_PERMISSIONS=(
  "zellij-autolock.wasm|ReadApplicationState ChangeApplicationState"
  "zjstatus.wasm|ReadApplicationState ChangeApplicationState RunCommands"
  "zjstatus-hints.wasm|ReadApplicationState MessageAndLaunchOtherPlugins"
  "zellij-newtab-plus.wasm|RunCommands Reconfigure ReadApplicationState ChangeApplicationState"
)
ZELLIJ_PERMISSIONS_FILE="$HOME/.cache/zellij/permissions.kdl"
mkdir -p "$(dirname "$ZELLIJ_PERMISSIONS_FILE")"
touch "$ZELLIJ_PERMISSIONS_FILE"
for entry in "${ZELLIJ_PLUGIN_PERMISSIONS[@]}"; do
  IFS='|' read -r dest perms <<<"$entry"
  plugin_path="${HOME}/.local/share/zellij/plugins/${dest}"
  if grep -qF "\"${plugin_path}\"" "$ZELLIJ_PERMISSIONS_FILE"; then
    continue
  fi
  {
    echo "\"${plugin_path}\" {"
    for perm in $perms; do
      echo "    ${perm}"
    done
    echo "}"
  } >>"$ZELLIJ_PERMISSIONS_FILE"
  ok "Pre-approved zellij permissions for ${dest}"
done

# ── Zsh: plugins (autosuggestions, syntax highlighting, alias reminders) ──────
# These plugins publish no GitHub Releases (no binary asset — just tagged
# source), so each is downloaded once as a full source tarball at a pinned
# tag rather than a single release asset like the Zellij plugins above. Same
# "don't hit the network on every shell start" reasoning: .zshrc sources the
# extracted .plugin.zsh entrypoint from a fixed local path (see zsh/.zshrc).
ZSH_PLUGIN_DIR="${SHARE_DIR}/zsh/plugins"
mkdir -p "$ZSH_PLUGIN_DIR"
ZSH_PLUGINS=(
  "zsh-autosuggestions|zsh-users/zsh-autosuggestions|v0.7.1"
  "zsh-syntax-highlighting|zsh-users/zsh-syntax-highlighting|0.8.0"
  "zsh-you-should-use|MichaelAquilina/zsh-you-should-use|1.11.1"
)
log "=== Zsh plugins ==="
for entry in "${ZSH_PLUGINS[@]}"; do
  IFS='|' read -r dest repo tag <<<"$entry"
  installed=$(get_installed_version "$dest")
  if [[ "$installed" == "$tag" && "$FORCE_UPDATE" == false ]]; then
    ok "${dest} already at ${tag}"
    continue
  fi
  log "Downloading ${dest} ${tag}..."
  zsh_plugin_tmp=$(mktemp -d)
  if curl -fL --connect-timeout 30 --max-time 120 --retry 2 \
    "https://github.com/${repo}/archive/refs/tags/${tag}.tar.gz" \
    -o "${zsh_plugin_tmp}/${dest}.tar.gz" &&
    tar -xzf "${zsh_plugin_tmp}/${dest}.tar.gz" -C "$zsh_plugin_tmp"; then
    src_dir=$(find "$zsh_plugin_tmp" -mindepth 1 -maxdepth 1 -type d | head -1)
    rm -rf "${ZSH_PLUGIN_DIR:?}/${dest}"
    mkdir -p "${ZSH_PLUGIN_DIR}/${dest}"
    cp -r "${src_dir}/." "${ZSH_PLUGIN_DIR}/${dest}/"
    set_installed_version "$dest" "$tag"
    ok "${dest} installed at ${tag}"
  else
    warn "Download failed for ${dest} — it won't load until this succeeds (re-run install.sh)"
  fi
  rm -rf "$zsh_plugin_tmp"
done

# link_package("bin") already ran above (before this Zellij/zsh plugins
# section existed), so any plugin just downloaded/built here has no
# ~/.local/share symlink yet — it fails to load silently until the next
# install.sh run. Re-link now so a fresh plugin works on the very first run.
link_package bin

# ── Fonts (Linux / macOS only — WSL defers to windows-setup.ps1) ─────────────
if [[ "$IS_WSL" == false ]]; then
  log "=== JetBrainsMono Nerd Font ==="
  FONT_KEY="jetbrainsmono-nf"
  installed_font_ver=$(get_installed_version "$FONT_KEY")

  font_api_response=""
  font_latest=""
  if [[ -z "$installed_font_ver" || "$FORCE_UPDATE" == true ]]; then
    font_api_response=$(curl -sf --connect-timeout 15 --retry 3 --retry-delay 2 \
      "${GITHUB_AUTH[@]}" "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest") || true
    font_latest=$(echo "$font_api_response" | grep -oP '"tag_name":\s*"\K[^"]+' | head -1) || true
  fi

  if [[ -n "$installed_font_ver" && "$FORCE_UPDATE" == false ]]; then
    ok "JetBrainsMono Nerd Font already at ${installed_font_ver}"
  elif [[ -z "$font_latest" ]]; then
    warn "Could not fetch JetBrainsMono Nerd Font version — skipping."
  elif [[ "$installed_font_ver" == "$font_latest" && "$FORCE_UPDATE" == false ]]; then
    ok "JetBrainsMono Nerd Font already at ${font_latest}"
  else
    log "Downloading JetBrainsMono Nerd Font ${font_latest}..."
    font_zip_url=$(echo "$font_api_response" |
      grep '"browser_download_url"' |
      grep 'JetBrainsMono\.zip' |
      cut -d'"' -f4 | head -1) || true

    if [[ -z "$font_zip_url" ]]; then
      warn "Could not find JetBrainsMono.zip asset — skipping font install."
    else
      font_tmp=$(mktemp -d)
      trap "rm -rf '$font_tmp'" RETURN

      if curl -fL --connect-timeout 30 --max-time 600 --retry 2 "$font_zip_url" -o "$font_tmp/JetBrainsMono.zip"; then
        unzip -q "$font_tmp/JetBrainsMono.zip" -d "$font_tmp/fonts"

        if [[ "$OS" == "darwin" ]]; then
          FONT_DEST="$HOME/Library/Fonts"
        else
          FONT_DEST="$HOME/.local/share/fonts"
        fi
        mkdir -p "$FONT_DEST"

        # Install NF, NFM, NFP — exclude NL variants (JetBrainsMonoNL*)
        font_count=0
        while IFS= read -r -d '' ttf; do
          cp "$ttf" "$FONT_DEST/"
          ((font_count++)) || true
        done < <(find "$font_tmp/fonts" -name "JetBrainsMonoNerdFont*.ttf" -print0)

        [[ "$OS" == "linux" ]] && fc-cache -f "$FONT_DEST" 2>/dev/null || true
        set_installed_version "$FONT_KEY" "$font_latest"
        ok "JetBrainsMono Nerd Font installed (${font_count} files) at ${font_latest}"
      else
        warn "Font download failed — skipping."
      fi
    fi
  fi
fi

# ── SSH socket directory ───────────────────────────────────────────────────────
mkdir -p "$HOME/.ssh/sockets"
chmod 700 "$HOME/.ssh"
[[ -f "$HOME/.ssh/config" ]] && chmod 600 "$HOME/.ssh/config" || true

# ── Windows / Alacritty setup (WSL2 only) ─────────────────────────────────────
if [[ "$IS_WSL" == true && "$NO_WINDOWS" == false ]]; then
  log "=== Windows setup (WSL2 detected) ==="

  # Check WSL interop before attempting any powershell.exe calls
  WSL_INTEROP_OK=false
  if [[ "$(head -1 /proc/sys/fs/binfmt_misc/WSLInterop 2>/dev/null)" == "enabled" ]]; then
    WSL_INTEROP_OK=true
  elif command -v powershell.exe &>/dev/null && powershell.exe -NonInteractive -c "exit 0" &>/dev/null; then
    WSL_INTEROP_OK=true
  fi

  if [[ "$WSL_INTEROP_OK" == false ]]; then
    warn "WSL interop is disabled — skipping Windows setup (Alacritty, fonts)."
    warn "To enable: add 'enabled=true' under [interop] in /etc/wsl.conf, then run 'wsl --shutdown' and reopen."
  else

    # Detect WSL distro name. $WSL_DISTRO_NAME is set by WSL itself for the
    # current session — use it first. Falling back to `wsl.exe --list --running`
    # picks the wrong distro (non-deterministic ordering) when more than one
    # distro is registered/running, e.g. a leftover install alongside the
    # current one, which silently points the Alacritty symlink at a path that
    # doesn't exist.
    DISTRO_NAME="${WSL_DISTRO_NAME:-}"
    [[ -z "$DISTRO_NAME" ]] &&
      DISTRO_NAME=$(powershell.exe -NonInteractive -c "wsl.exe --list --running --quiet" 2>/dev/null |
        tr -d '\r\0' | grep -v '^$' | head -1) || true
    [[ -z "$DISTRO_NAME" ]] &&
      DISTRO_NAME=$(grep "^NAME=" /etc/os-release 2>/dev/null | cut -d'"' -f2 | tr ' ' '-') || true

    # Build Windows path to the alacritty.toml source file in dotfiles
    WIN_CONFIG_TARGET=""
    if [[ "$DOTFILES" =~ ^/mnt/([a-zA-Z])(/.*)$ ]]; then
      DRIVE="${BASH_REMATCH[1]^^}"
      REST="${BASH_REMATCH[2]}"
      WIN_CONFIG_TARGET="${DRIVE}:${REST//\//\\}\\alacritty\\.config\\alacritty\\alacritty.toml"
    else
      WIN_CONFIG_TARGET="\\\\wsl.localhost\\${DISTRO_NAME}${DOTFILES//\//\\}\\alacritty\\.config\\alacritty\\alacritty.toml"
    fi

    PS_WIN_PATH=$(wslpath -w "$DOTFILES/windows-setup.ps1")
    log "Running Windows setup (Alacritty, font, config)..."
    powershell.exe -NonInteractive -ExecutionPolicy Bypass \
      -File "$PS_WIN_PATH" -AlacrittyTarget "$WIN_CONFIG_TARGET" 2>&1 |
      tr -d '\r\0' | grep -v "^$" ||
      warn "PowerShell step had warnings (non-fatal)"

  fi # end WSL_INTEROP_OK
fi   # end IS_WSL

# ── Cleanup: orphaned installs and dead toolchains (--cleanup) ────────────────
# Reads CORE_TOOLS/CLI_TOOLS/ZELLIJ_PLUGINS/ZSH_PLUGINS — the same arrays used
# to install everything above — as the single source of truth for "what
# install.sh currently knows about." Anything else recorded in $VERSIONS_FILE
# is orphaned: a tool renamed/removed from those arrays (or from a dedicated
# installer like ccusage's, after it was dropped entirely) whose downloaded
# file just never gets touched again by the overwrite-in-place download
# functions, so it sits there forever unless something explicitly diffs
# against the current tool list — which is what this does.
cleanup_orphans() {
  log "=== Cleanup ==="

  # rustup/cargo: only bootstrapped under --cargo (see USE_CARGO above); if
  # this run didn't ask for --cargo, any toolchain on disk is left over from
  # a past --cargo run (or, before the Nushell->zsh migration, from cargo
  # running unconditionally) — dead weight, regenerated on demand by the next
  # --cargo run.
  if [[ "$USE_CARGO" == false ]]; then
    local cleaned_toolchain=false size
    if [[ -d "$HOME/.rustup" ]]; then
      size=$(du -sh "$HOME/.rustup" 2>/dev/null | cut -f1)
      rm -rf "$HOME/.rustup"
      ok "Removed ~/.rustup (${size:-?})"
      cleaned_toolchain=true
    fi
    if [[ -d "$HOME/.cargo" ]]; then
      size=$(du -sh "$HOME/.cargo" 2>/dev/null | cut -f1)
      rm -rf "$HOME/.cargo"
      ok "Removed ~/.cargo (${size:-?})"
      cleaned_toolchain=true
    fi
    [[ "$cleaned_toolchain" == false ]] && ok "No rustup/cargo toolchain to clean up"
  else
    ok "Skipping rustup/cargo cleanup (this run used --cargo)"
  fi

  # Build the known-dest set from the exact arrays used to install things
  # above, plus the handful of installers that don't use those arrays (nvim
  # has its own bespoke installer, always known; node/ccstatusline are only
  # known when this run wants the Claude Code stack — see
  # WANT_CLAUDE_STACK — same as pwsh only being known under --full).
  local -A known_dest=()
  local t dest_field
  for t in "${CORE_TOOLS[@]}" "${CLI_TOOLS[@]}"; do
    dest_field="${t%%|*}"
    known_dest["$dest_field"]=1
  done
  known_dest["nvim"]=1
  known_dest["yazi"]=1
  known_dest["jetbrainsmono-nf"]=1
  if [[ "$WANT_CLAUDE_STACK" == true ]]; then
    known_dest["node"]=1
    known_dest["ccstatusline"]=1
  fi
  [[ "$FULL_INSTALL" == true ]] && known_dest["pwsh"]=1

  local -A known_zellij=() known_zsh=()
  for t in "${ZELLIJ_PLUGINS[@]}"; do
    dest_field="${t%%|*}"
    known_zellij["$dest_field"]=1
  done
  for t in "${ZSH_PLUGINS[@]}"; do
    dest_field="${t%%|*}"
    known_zsh["$dest_field"]=1
  done

  # Single read pass over .versions (materialized into memory first — this
  # loop's body does deletions, and rewriting the file mid-iteration over its
  # own file descriptor is a footgun worth just avoiding outright), one
  # optional rewrite pass at the end excluding whatever got orphan-cleaned.
  local -a versions_lines=()
  local -A to_remove=()
  mapfile -t versions_lines <"$VERSIONS_FILE"

  local line key ver npm_dir
  for line in "${versions_lines[@]}"; do
    [[ -z "$line" ]] && continue
    key="${line%%=*}"
    ver="${line#*=}"

    if [[ -n "${known_dest[$key]:-}" || -n "${known_zellij[$key]:-}" || -n "${known_zsh[$key]:-}" ]]; then
      continue
    elif [[ "$key" == "pwsh" ]]; then
      # Only reachable when FULL_INSTALL == false (known_dest has it
      # otherwise) — orphaned from a previous --full run.
      if [[ -d "$HOME/.local/lib/powershell" ]]; then
        size=$(du -sh "$HOME/.local/lib/powershell" 2>/dev/null | cut -f1)
        rm -rf "$HOME/.local/lib/powershell"
        rm -f "$LOCAL_BIN/pwsh"
        ok "Removed orphaned pwsh ${ver} (${size:-?}) — use --full to reinstall"
      fi
      to_remove["$key"]=1
    elif [[ -f "$BIN_DIR/$key" ]]; then
      rm -f "$BIN_DIR/$key"
      ok "Removed orphaned binary: ${key} ${ver}"
      to_remove["$key"]=1
    elif [[ -f "${ZELLIJ_PLUGIN_DIR}/${key}" ]]; then
      rm -f "${ZELLIJ_PLUGIN_DIR}/${key}"
      ok "Removed orphaned Zellij plugin: ${key} ${ver}"
      to_remove["$key"]=1
    elif [[ -d "${ZSH_PLUGIN_DIR}/${key}" ]]; then
      rm -rf "${ZSH_PLUGIN_DIR}/${key}"
      ok "Removed orphaned zsh plugin: ${key} ${ver}"
      to_remove["$key"]=1
    elif npm_dir="$HOME/.local/lib/node_modules/$key" && [[ -d "$npm_dir" ]] && command -v npm &>/dev/null; then
      if npm uninstall -g "$key" --prefix "$HOME/.local" </dev/null &>/dev/null; then
        ok "Removed orphaned npm global: ${key} ${ver}"
      else
        warn "npm uninstall failed for orphaned global ${key} — remove manually: rm -rf ${npm_dir}"
      fi
      to_remove["$key"]=1
    elif [[ "$key" == "node" ]]; then
      # Only reachable when WANT_CLAUDE_STACK == false (known_dest has it
      # otherwise) — orphaned because nothing wants the Claude Code stack
      # this run. Deliberately not auto-removed: install_node's cp -a merges
      # node's bin/lib/include/share trees straight into the same
      # ~/.local/{bin,lib,...} directories real dotfiles-deployed symlinks
      # and other npm globals live in, so there's no single owned path to
      # rm -rf the way pwsh's isolated ~/.local/lib/powershell is above —
      # guessing wrong here risks deleting files this script doesn't own.
      warn "node (${ver}) is orphaned (nothing wants --claude/--full this run) but isn't auto-removed — its files are merged into ~/.local/{bin,lib,include,share} alongside things this script doesn't own; clean up by hand if you're sure nothing else needs it"
    else
      warn ".versions has '${key}=${ver}' but nothing on disk matches it anywhere known — leaving it (remove by hand if actually stale)"
    fi
  done

  if [[ ${#to_remove[@]} -gt 0 ]]; then
    local tmp_versions
    tmp_versions=$(mktemp)
    for line in "${versions_lines[@]}"; do
      [[ -z "$line" ]] && continue
      key="${line%%=*}"
      [[ -n "${to_remove[$key]:-}" ]] && continue
      echo "$line" >>"$tmp_versions"
    done
    mv "$tmp_versions" "$VERSIONS_FILE"
    ok "Pruned ${#to_remove[@]} orphaned entr$([[ ${#to_remove[@]} -eq 1 ]] && echo y || echo ies) from .versions"
  else
    ok "No orphaned .versions entries found"
  fi

  # Neovim's Mason-managed --full-only LSP packages (see the --full section
  # above, lua/config/lazy.lua, and lua/plugins/lsp-servers.lua). install.sh
  # doesn't install these itself — Mason downloads them lazily inside nvim —
  # so they can't be caught by the .versions scan above; this list has to be
  # kept in sync by hand with what those two nvim files gate on full_install.
  if [[ "$FULL_INSTALL" == false && -d "$HOME/.local/share/nvim/mason/packages" ]]; then
    local -a full_only_mason=(html-lsp css-lsp emmet-language-server bash-language-server
      pyright intelephense phpactor php-cs-fixer phpcs powershell-editor-services)
    local -a mason_to_remove=()
    local pkg
    for pkg in "${full_only_mason[@]}"; do
      [[ -d "$HOME/.local/share/nvim/mason/packages/$pkg" ]] && mason_to_remove+=("$pkg")
    done
    if [[ ${#mason_to_remove[@]} -gt 0 ]]; then
      if command -v nvim &>/dev/null; then
        log "Uninstalling ${#mason_to_remove[@]} full-install-only Mason package(s): ${mason_to_remove[*]}"
        nvim --headless \
          -c "lua require('lazy').load({plugins={'mason.nvim'}})" \
          -c "lua vim.wait(300)" \
          -c "MasonUninstall ${mason_to_remove[*]}" \
          -c "lua vim.wait(3000)" \
          -c "qa" </dev/null &>/dev/null || true
        ok "Mason cleanup done"
      else
        warn "nvim not found — can't clean up ${#mason_to_remove[@]} orphaned Mason package(s), run :MasonUninstall manually"
      fi
    else
      ok "No orphaned full-install-only Mason packages found"
    fi
  fi

  # Claude Code's own native self-updater, not install.sh, manages
  # ~/.local/bin/claude — it's a symlink into ~/.local/share/claude/versions/,
  # and every self-update drops a new ~300MB+ version binary there without
  # ever deleting the old ones. Not caught by the .versions scan above (that
  # file only tracks what install.sh itself downloaded); handled separately
  # here by just diffing the versions dir against whatever the symlink
  # currently resolves to.
  if [[ -d "$HOME/.local/share/claude/versions" ]]; then
    local current_claude cleaned_claude=false ver_path ver_name
    current_claude=$(readlink -f "$HOME/.local/bin/claude" 2>/dev/null || true)
    for ver_path in "$HOME/.local/share/claude/versions"/*; do
      [[ -e "$ver_path" ]] || continue
      if [[ -z "$current_claude" || "$ver_path" != "$current_claude" ]]; then
        ver_name=$(basename "$ver_path")
        size=$(du -sh "$ver_path" 2>/dev/null | cut -f1)
        rm -f "$ver_path"
        ok "Removed old Claude Code version: ${ver_name} (${size:-?})"
        cleaned_claude=true
      fi
    done
    [[ "$cleaned_claude" == false ]] && ok "No orphaned Claude Code versions to clean up"
  fi
}
if [[ "$DO_CLEANUP" == true ]]; then
  if [[ "$LINK_ONLY" == true ]]; then
    warn "--cleanup has no effect combined with --link — the tool arrays it diffs against are never populated without a real run."
  else
    cleanup_orphans
    # Orphaned $BIN_DIR/ZELLIJ_PLUGIN_DIR/ZSH_PLUGIN_DIR files just got deleted
    # from the repo tree above, which leaves their deployed ~/.local symlinks
    # dangling — prune_stale_symlinks (defined earlier, already ran once
    # before configs were linked) sweeps exactly those.
    prune_stale_symlinks
  fi
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}╔══════════════════════════════════════════════════╗${RESET}"
echo -e "${BOLD}${GREEN}║        Dotfiles installed successfully!          ║${RESET}"
echo -e "${BOLD}${GREEN}╚══════════════════════════════════════════════════╝${RESET}"
echo ""
echo -e "${CYAN}Next steps:${RESET}"
echo "  1. Open a new terminal — zsh is now the default shell, and Zellij auto-starts"
echo "  2. Press \` to enter Zellij prefix mode"
echo "  3. Open Neovim:    nvim  (then :Lazy sync to install plugins)"
echo "  4. Update all:     ./install.sh --update"
echo ""
if [[ "$IS_WSL" == true ]]; then
  echo -e "${CYAN}Windows:${RESET}"
  echo "  • Open Alacritty — font and theme should load automatically"
  echo "  • If symlink failed, see manual steps printed above"
  echo ""
fi
