"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_surface0)\
$os\
$time\
[](fg:prev_bg bg:color_maroon)\
$sudo\
$username\
$hostname\
[](fg:prev_bg bg:color_yellow)\
$directory\
[](fg:prev_bg bg:color_teal)\
$git_branch\
$git_commit\
$git_status\
[](fg:prev_bg bg:color_blue)\
$rust\
$nodejs\
$php\
$python\
[](fg:prev_bg bg:color_mauve)\
$docker_context\
$jobs\
[](fg:prev_bg bg:color_surface0)\
$cmd_duration\
[](fg:prev_bg)\
$line_break$character"""


# Options
palette = 'catppuccin_mocha'
continuation_prompt = '--> '
add_newline = true

# Modules (in used order)
# Gray Pill
[os]
disabled = false
style = "bg:prev_bg fg:color_crust"
format = "[$symbol]($style)"

[time]
disabled = false
time_format = "%F %R:%6f"
style = "bg:prev_bg fg:color_text "
format = '[$time ]($style)'

# Red Pill

[sudo]
symbol = "󱎚"
disabled = false
style = "bg:prev_bg fg:color_crust"
format = "[$symbolSUDO ]($style)"

[username]
show_always = true
style_user = "bg:prev_bg fg:color_crust"
style_root = "bg:prev_bg fg:prev_fg"
format = '[$user]($style)'

[hostname]
ssh_symbol = ""
ssh_only = false
trim_at = '.l'
style = "bg:prev_bg fg:prev_fg "
format = "[@$hostname ($ssh_symbol )]($style)"

# Yellow Pill

[directory]
read_only = "󰌾"
truncate_to_repo = false
truncation_length = 10
truncation_symbol = "…/"
style = "bg:prev_bg fg:color_crust"
format = "[($read_only)]($style)[$path ]($style)"

# Green Pill

[git_branch]
symbol = ""
style = "bg:prev_bg fg:color_crust "
format = "[$symbol$branch ]($style)"

[git_commit]
tag_symbol = "🏷"
commit_hash_length = 7
style = "bg:prev_bg fg:prev_fg"
format = "[$hash$tag ]($style)"	

[git_status]
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = '[($all_status$ahead_behind )]($style)'

# Blue Pill

[rust]
symbol = ""
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = '[$symbol( $version) ]($style)'

[nodejs]
symbol = ""
style = "fbg:prev_bg g:color_crust"
format = '[$symbol( $version) ](fg:color_crust bg:prev_bg)' # bug, must set explicitly

[php]
symbol = ""
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = '[$symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = '[$symbol( $version)( $virtualenv) ]($style)' 

# Purple Pill

[docker_context]
symbol = ""
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = '[$symbol( $context) ]($style)'

[jobs]
symbol = "󰆅"
symbol_threshold = 2
number_threshold = 2
style = "bg:prev_bg fg:color_crust" # fg redefined, as prev module may not exist
format = "[$symbol($number )]($style)"

# Gray Pill

[cmd_duration]
min_time = 1_000
show_milliseconds = true
style = "bg:prev_bg fg:prev_fg"
format = "[$duration ]($style)"

# New Line

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'

# Theme

[palettes.catppuccin_mocha]
color_rosewater = "#f5e0dc"
color_flamingo = "#f2cdcd"
color_pink = "#f5c2e7"
color_mauve = "#cba6f7"
color_red = "#f38ba8"
color_maroon = "#eba0ac"
color_peach = "#fab387"
color_yellow = "#f9e2af"
color_green = "#a6e3a1"
color_teal = "#94e2d5"
color_sky = "#89dceb"
color_sapphire = "#74c7ec"
color_blue = "#89b4fa"
color_lavender = "#b4befe"
color_text = "#cdd6f4" 
color_subtext1 = "#bac2de"
color_subtext0 = "#a6adc8"
color_overlay2 = "#9399b2"
color_overlay1 = "#7f849c"
color_overlay0 = "#6c7086"
color_surface2 = "#585b70"
color_surface1 = "#45475a" 
color_surface0 = "#313244"
color_base = "#1e1e2e"
color_mantle = "#181825"
color_crust = "#11111b"

# OS Symbols

[os.symbols]
Alpine = "[](fg:color_teal bg:prev_fg)"
Amazon = "[](fg:color_peach bg:prev_fg)"
Android = "[](fg:color_green bg:prev_fg)"
Arch = "[󰣇](fg:color_blue bg:prev_fg)"
Artix = "[󰣇](fg:color_blue bg:prev_fg)"
CachyOS = "[󰣇](fg:color_blue bg:prev_fg)"
CentOS = "[](fg:color_blue bg:prev_fg)"
Debian = "[󰣚](fg:color_red bg:prev_fg)"
Elementary = "[](fg:color_text bg:prev_fg)"
EndeavourOS = "[](fg:color_purple bg:prev_fg)"
Fedora = "[󰣛](fg:color_red bg:prev_fg)"
FreeBSD = "[](fg:color_red bg:prev_fg)"
Gentoo = "[󰣨](fg:color_text bg:prev_fg)"
Kali = "[](fg:color_text bg:prev_fg)"
Linux = "[󰌽](fg:color_text bg:prev_fg)"
Macos = "[󰀵](fg:color_text bg:prev_fg)"
Manjaro = "[](fg:color_green bg:prev_fg)"
Mint = "[󰣭](fg:color_green bg:prev_fg)"
Pop = "[](fg:color_teal bg:prev_fg)"
Raspbian = "[󰐿](fg:color_red bg:prev_fg)"
RedHatEnterprise = "[󱄛](fg:color_red bg:prev_fg)"
Redhat = "[󱄛](fg:color_red bg:prev_fg)"
SUSE = "[](fg:color_green bg:prev_fg)"
Ubuntu = "[](fg:color_peach bg:prev_fg)"
Windows = "[](fg:color_blue bg:prev_fg)"